name: Notify to Slack
description: Notify the status of GitHub Actions to Slack App
inputs:
  status:
    description: >
      status message to be posted, which can be "success", "failure",
      or any other string
    required: true
  color:
    description: >
      color of the border on the left side of the attachment,
      which can be one of "good" (green), "warning" (yellow), "danger" (red),
      or any hex color code "#xxxxxx"
    required: false
    default: ''
runs:
  using: composite
  steps:
    - run: |
        : Check if environment variables exist
        err=0
        for var in CHANNEL_ID BOT_USER_OAUTH_TOKEN; do
          [[ -v $var ]] && continue
          echo $var: unbound variable >&2
          err=1
        done
        exit $err
      shell: bash
    - id: color
      run: |
        : Choose color from input status when not specified
        inputs_color='${{ inputs.color }}'
        status_color=warning
        test '${{ inputs.status }}' = success && status_color=good
        test '${{ inputs.status }}' = failure && status_color=danger
        echo ::set-output name=color::${inputs_color:-$status_color}
      shell: bash
    - uses: slackapi/slack-github-action@v1.16.0
      with:
        channel-id: ${{ env.CHANNEL_ID }}
        payload: >
          {
            "text": " ",
            "attachments": [
              {
                "mrkdwn_in": ["text", "footer"],
                "fallback": "${{ env.FALLBACK }}",
                "color": "${{ steps.color.outputs.color }}",
                "text": "${{
                  format('{0} {1}: <{2}/actions/runs/{3}|#{4}>',
                    github.workflow,
                    inputs.status,
                    github.event.repository.url,
                    github.run_id,
                    github.run_number)
                }}",
                "footer": "${{
                  format('<{0}|{1}>',
                    github.event.repository.url,
                    github.event.repository.full_name)
                }}",
                "footer_icon": "${{ env.ICON_URL }}"
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ env.BOT_USER_OAUTH_TOKEN }}
        FALLBACK: GitHub Actions Notification
        ICON_URL: https://slack.github.com/static/img/favicon-neutral.png
