function(develop_flag_option)
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.develop")
    set(flag ON)
  else()
    set(flag OFF)
  endif()
  option(DEVELOP_FLAG "Development mode" ${flag})
  mark_as_advanced(DEVELOP_FLAG)
endfunction()
