# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_type: Release
            build_dir: release
          - build_type: Debug
            build_dir: debug
      fail-fast: false
      max-parallel: 2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Versions
        run: for cmd in clang flex bison make cmake; do $cmd --version | head -n1; done

      - name: Test
        env:
          BUILD_DIR: ${{ matrix.build_dir }}
        run: ./test.sh -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Notify
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "color": "#28A745",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "plain_text",
                          "text": "github.action: ${{ github.action }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.action_path: ${{ github.action_path }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.actor: ${{ github.actor }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.base_ref: ${{ github.base_ref }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.event: ${{ github.event }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.event_name: ${{ github.event_name }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.event_path: ${{ github.event_path }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.head_ref: ${{ github.head_ref }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.job: ${{ github.job }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.ref: ${{ github.ref }}"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "plain_text",
                          "text": "github.ref_name: ${{ github.ref_name }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.repository: ${{ github.repository }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.repository_owner: ${{ github.repository_owner }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.run_id: ${{ github.run_id }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.run_number: ${{ github.run_number }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.run_attempt: ${{ github.run_attempt }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.server_url: ${{ github.server_url }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.sha: ${{ github.sha }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.workflow: ${{ github.workflow }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "github.workspace: ${{ github.workspace }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
