name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Versions
        run: for cmd in clang flex bison make cmake; do $cmd --version | head -n1; done
      - name: Test
        env:
          BUILD_DIR: ${{ matrix.build_dir }}
        run: ./test.sh -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - run: test ${{ matrix.build_type }} = Release || exit
    strategy:
      matrix:
        include:
          - build_type: Release
            build_dir: release
          - build_type: Debug
            build_dir: debug
      fail-fast: false
      max-parallel: 2
  notify:
    name: Notify
    needs: build
    runs-on: ubuntu-latest
    if: always()
    strategy:
      matrix:
        include:
          - status: success
            color: good
            text: ${{ github.workflow }} Success
          - status: failure
            color: danger
            text: "${{ github.workflow }} Failed: <${{ env.ACTION_URL }}|#${{ github.run_number }}> ${{ github.event.head_commit.message }}"
    steps:
      - if: needs.build.result == matrix.status
        name: Notify ${{ matrix.status }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "fallback": "GitHub Actions Notification",
                  "color": "${{ matrix.color }}",
                  "text": "${{ matrix.text }}",
                  "footer": "${{ env.FOOTER }}",
                  "footer_icon": "${{ env.ICON }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          ACTION_URL: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}
          FOOTER: <${{ github.event.repository.url }}|${{ github.event.repository.full_name }}>
          ICON: https://slack.github.com/static/img/favicon-neutral.png
