name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Versions
        run: for cmd in clang flex bison make cmake; do $cmd --version | head -n1; done
      - name: Test
        env:
          BUILD_DIR: ${{ matrix.build_dir }}
        run: ./test.sh -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - run: test ${{ matrix.build_type }} = Release || exit
    strategy:
      matrix:
        include:
          - build_type: Release
            build_dir: release
          - build_type: Debug
            build_dir: debug
      fail-fast: false
      max-parallel: 2
    continue-on-error: true
  notify-success:
    name: Notify Success
    needs: build
    runs-on: ubuntu-latest
#   if: needs.build.result == 'success'
    steps:
      - run: echo '${{ toJSON(needs) }}'
      - name: Notify
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "fallback": "GitHub Actions Notification",
                  "color": "good",
                  "text": "${{ github.workflow }} Success",
                  "footer": "<${{ github.event.repository.url }}|${{ github.event.repository.full_name }}>",
                  "footer_icon": "https://slack.github.com/static/img/favicon-neutral.png"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  notify-failure:
    name: Notify Failure
    needs: build
    runs-on: ubuntu-latest
#   if: needs.build.result == 'failure'
    steps:
      - run: echo '${{ toJSON(needs) }}'
      - name: Notify
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "fallback": "GitHub Actions Notification",
                  "color": "danger",
                  "text": "${{ github.workflow }} Failed: <${{ env.ACTION_URL }}|#${{ github.run_number }}> ${{ github.event.head_commit.message }}",
                  "footer": "<${{ github.event.repository.url }}|${{ github.event.repository.full_name }}>",
                  "footer_icon": "https://slack.github.com/static/img/favicon-neutral.png"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          ACTION_URL: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}
