name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Versions
        run: for cmd in clang flex bison make cmake; do $cmd --version | head -n1; done
      - name: Test
        env:
          BUILD_DIR: ${{ matrix.build_dir }}
        run: ./test.sh -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - run: test ${{ matrix.build_type }} = Release || exit
    strategy:
      matrix:
        include:
          - build_type: Release
            build_dir: release
          - build_type: Debug
            build_dir: debug
      fail-fast: false
      max-parallel: 2
  notify:
    name: Notify
    needs: build
    runs-on: ubuntu-latest
    env:
      MESSAGE: ${{ github.event.head_commit.message }}
      REPO_URL: ${{ github.event.repository.url }}
      FULL_NAME: ${{ github.event.repository.full_name }}
      ACTION_LINK: ${{ format('<{0}/actions/runs/{1}|#{2}>', env.REPO_URL, github.run_id, github.run_number) }}
      FOOTER_LINK: ${{ format('<{0}|{1}>', env.REPO_URL, env.FULL_NAME) }}
      ICON_URL: https://slack.github.com/static/img/favicon-neutral.png
    if: always()
    steps:
      - if: needs.build.result == matrix.status
        name: Notify ${{ matrix.status }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "fallback": "GitHub Actions Notification",
                  "color": "${{ matrix.color }}",
                  "text": "${{ join([github.workflow, format('{0}:', matrix.txt), env.ACTION_LINK, env.MESSAGE], ' ') }}",
                  "footer": "${{ env.FOOTER_LINK }}",
                  "footer_icon": "${{ env.ICON_URL }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    strategy:
      matrix:
        include:
          - status: success
            text: Success
            color: good
          - status: failure
            text: Failed
            color: danger
