name: CI
on:
  push:
    branches: [ master, ci-debug ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ matrix.build_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Versions
        run: |
          for cmd in clang flex bison make cmake; do
            $cmd --version | head -n1
          done
      - name: Build
        run: ./build.sh -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Test
        run: ./test.sh
    strategy:
      matrix:
        build_type: [Release, Debug]
      fail-fast: false
      max-parallel: 2
  notify:
    name: Notify
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: needs.test.result == matrix.status
        name: Checkout
        uses: actions/checkout@v2
      - if: needs.test.result == matrix.status
        name: Notify ${{ matrix.status }}
        uses: ./.github/actions/notify-to-slack
        with:
          status: ${{ matrix.status }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_USER_OAUTH_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
    strategy:
      matrix:
        status: [success, failure]
