# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_type: Release
            build_dir: release
          - build_type: Debug
            build_dir: debug
      fail-fast: false
      max-parallel: 2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Versions
        run: for cmd in clang flex bison make cmake; do $cmd --version | head -n1; done

      - name: Test
        env:
          BUILD_DIR: ${{ matrix.build_dir }}
        run: ./test.sh -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Notify
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "color": "#28A745",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "plain_text",
                          "text": $values.test
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        values: |
          test: $GITHUB_WORKFLOW, ${GITHUB_WORKFLOW}, ${{ GITHUB_WORKFLOW }}
